version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_bank
    restart: always
    environment:
      POSTGRES_DB: galleria_bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: galleria_backend
    restart: unless-stopped
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/galleria_bank
      DB_USER: admin
      DB_PASS: admin
      JWT_SECRET: super-secret
      JWT_EXPIRATION: 86400000
volumes:
  postgres_data:
